export const FETCH_ALL_MOVIES_REQUEST = "FETCH_ALL_MOVIES_REQUEST";
export const FETCH_ALL_MOVIES_SUCCESS = "FETCH_ALL_MOVIES_SUCCESS";
export const FETCH_ALL_MOVIES_FAILURE = "FETCH_ALL_MOVIES_FAILURE";
